### PR TITLE
Add globbing and compression to edge

### PR DESCRIPTION
**Pull request by garethlewin**
This change is [Reviewable](https://reviewable.io/reviews/twitchscience/spade_edge/19)

### CODE REVIEW

**Comment by mjperrone** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[loggers/kinesis.go, line 23 \[r1\]](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-KJvWoqQuAlTYMUucSoy:-KJvWoqQuAlTYMUucSoz:678055703) ([raw file](https://github.com/twitchscience/spade_edge/blob/c7d01c5c79700b2c0bab00ea4a310e8afbffa83e/loggers/kinesis.go#L23)):*
> ```Go
> 
> var (
> 	kinesisStatsPrefix = "logger.kinesis."
> ```

test

---

*[loggers/kinesis.go, line 30 \[r1\]](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-KJvWtNkHoVL4saM7Qpv:-KJvWtNkHoVL4saM7Qpw:-455109637) ([raw file](https://github.com/twitchscience/spade_edge/blob/1263b68a1bf95be2ab5bf37865ce10f52dfa3461/loggers/kinesis.go#L30)):*
> ```Go
> 
> // KinesisLoggerConfig is used to configure a new SpadeEdgeLogger that writes to
> // an AWS Kinesis stream. There are no default values and all fields are required.
> ```

test2

---

*[loggers/kinesis.go, line 32 \[r1\]](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-KJvWsWmqGwq3umqbLcm:-KJvWsWmqGwq3umqbLcn:-455109638) ([raw file](https://github.com/twitchscience/spade_edge/blob/c7d01c5c79700b2c0bab00ea4a310e8afbffa83e/loggers/kinesis.go#L32)):*
> ```Go
> 	StreamName string
> 
> 	// BatchLength is the max amount of events per batch sent to Kinesis
> ```

test1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/twitchscience/spade_edge/19)*

**Comment by mjperrone** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/twitchscience/spade_edge/19)*

**Comment by GarethLewin** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/twitchscience/spade_edge/19)*

**Comment by mjperrone** [comment]
:lgtm:

<details><summary><i>Previously, GarethLewin (Gareth Lewin) wrote…</i></summary>
> #### Add globbing and compression to edge
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-:-KJvpiHgAJes930gwxCA:1417088721)*

**Comment by GarethLewin** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[loggers/kinesis.go, line 23 \[r1\]](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-KJvWoqQuAlTYMUucSoy:-KJvpsXyBdAN5Ti6HmwH:-499146009) ([raw file](https://github.com/twitchscience/spade_edge/blob/c7d01c5c79700b2c0bab00ea4a310e8afbffa83e/loggers/kinesis.go#L23)):*
<details><summary><i>Previously, mjperrone (Mike Perrone) wrote…</i></summary>
> test
</details>
Done.

---

*[loggers/kinesis.go, line 30 \[r1\]](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-KJvWtNkHoVL4saM7Qpv:-KJvpsvXXLx2irBb7Ksl:-499146009) ([raw file](https://github.com/twitchscience/spade_edge/blob/1263b68a1bf95be2ab5bf37865ce10f52dfa3461/loggers/kinesis.go#L30)):*
<details><summary><i>Previously, mjperrone (Mike Perrone) wrote…</i></summary>
> test2
</details>
Done.

---

*[loggers/kinesis.go, line 32 \[r1\]](https://reviewable.io:443/reviews/twitchscience/spade_edge/19#-KJvWsWmqGwq3umqbLcm:-KJvptOSZA5k-SG1YJcg:-499146009) ([raw file](https://github.com/twitchscience/spade_edge/blob/c7d01c5c79700b2c0bab00ea4a310e8afbffa83e/loggers/kinesis.go#L32)):*
<details><summary><i>Previously, mjperrone (Mike Perrone) wrote…</i></summary>
> test1
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/twitchscience/spade_edge/19)*

**Pull request merged**
